### PR TITLE
Develop indra

### PR DESCRIPTION
**Pull request by Pogman**
Ready for testing - "Indra"

Realtime history and cgm backfill - all your treatment info and cgm data with no gaps.

### CODE REVIEW

**Comment by volkerrichert** [comment]
Hi! I try to build it, but 2 drawable are missing
Error:error: resource drawable/ic_busy (aka info.nightscout.android:drawable/ic_busy) not found.
Error:error: resource drawable/ic_notification (aka info.nightscout.android:drawable/ic_notification) not found.

**Comment by whooze** [comment]
Yeah, I got the same thing but didn’t post about it here cause I feel lost in Android Studio and thought I did something wrong. Also had to download a missing jar, don’t remember which one now but can check it I t later tonight

**Comment by Pogman** [comment]
Some files are not getting versioned to git - sorting that out now - come back in 1/2 hour :)

**Comment by whooze** [comment]
OMG. 

Will this be the best Christmas Eve ever?!? :)
Really looking forward to test this build

**Comment by volkerrichert** [comment]
ok, after tons of queries i got 

12-24 18:05:20.993 7114-11554/info.nightscout.android D/NightScoutUpload: queued item for nightscout treatments bulk upload, KEY: BG807B1C36
12-24 18:05:21.008 7114-11554/info.nightscout.android D/OkHttp: --> GET https://carelink.richert.nrw/api/v1/treatments.json?find[created_at][$gte]=2017&find[key600]=BG807B08EC http/1.1
12-24 18:05:21.008 7114-11554/info.nightscout.android D/OkHttp: api-secret: dcd0902ec046640859593b86d6d09c5521858ba5
12-24 18:05:21.008 7114-11554/info.nightscout.android D/OkHttp: --> END GET
12-24 18:05:21.155 7114-11554/info.nightscout.android D/OkHttp: <-- 200 OK https://carelink.richert.nrw/api/v1/treatments.json?find[created_at][$gte]=2017&find[key600]=BG807B08EC (145ms)
12-24 18:05:21.155 7114-11554/info.nightscout.android D/OkHttp: X-Powered-By: Express
12-24 18:05:21.155 7114-11554/info.nightscout.android D/OkHttp: Content-Type: application/json; charset=utf-8
12-24 18:05:21.155 7114-11554/info.nightscout.android D/OkHttp: Content-Length: 2
12-24 18:05:21.155 7114-11554/info.nightscout.android D/OkHttp: ETag: W/"2-l9Fw4VUO7kr8CvBlt4zaMCqXZ0w"
12-24 18:05:21.155 7114-11554/info.nightscout.android D/OkHttp: Vary: Accept-Encoding
12-24 18:05:21.155 7114-11554/info.nightscout.android D/OkHttp: Date: Sun, 24 Dec 2017 17:05:22 GMT
12-24 18:05:21.157 7114-11554/info.nightscout.android D/OkHttp: []
12-24 18:05:21.158 7114-11554/info.nightscout.android D/OkHttp: <-- END HTTP (2-byte body)
12-24 18:05:21.160 7114-11554/info.nightscout.android D/NightScoutUpload: queued item for nightscout treatments bulk upload, KEY: BG807B08EC
12-24 18:05:21.216 7114-7114/info.nightscout.android I/MasterService: Message Receiver: {ion_alert_circled} Error uploading: length=488; index=488
12-24 18:05:21.216 7114-7114/info.nightscout.android D/UserLogMessage: addMessage: {ion_alert_circled} Error uploading: length=488; index=488
12-24 18:05:21.221 7114-11554/info.nightscout.android E/NightscoutUploadService: ERROR uploading data!!!!!
                                                                                 java.lang.ArrayIndexOutOfBoundsException: length=488; index=488
                                                                                     at info.nightscout.android.utils.ToolKit.read8toUInt(ToolKit.java:42)
                                                                                     at info.nightscout.android.model.medtronicNg.PumpHistoryProfile$BasalProfile.parseBasalPattern(PumpHistoryProfile.java:193)
                                                                                     at info.nightscout.android.model.medtronicNg.PumpHistoryProfile$BasalProfile.makeProfile(PumpHistoryProfile.java:175)
                                                                                     at info.nightscout.android.model.medtronicNg.PumpHistoryProfile$BasalProfile.access$400(PumpHistoryProfile.java:147)
                                                                                     at info.nightscout.android.model.medtronicNg.PumpHistoryProfile.nightscout(PumpHistoryProfile.java:140)
                                                                                     at info.nightscout.android.upload.nightscout.NightScoutUpload.uploadEvents(NightScoutUpload.java:89)
                                                                                     at info.nightscout.android.upload.nightscout.NightScoutUpload.doRESTUpload(NightScoutUpload.java:72)
                                                                                     at info.nightscout.android.upload.nightscout.NightscoutUploadService$Upload.run(NightscoutUploadService.java:91)
12-24 18:05:21.221 7114-11554/info.nightscout.android D/PumpHistoryHandler: close history handler

**Pull request merged**
